config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orders.urls', namespace='orders'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders.apps import OrdersConfig
from orders.views import (OrderCreateAPIView, OrderListAPIView, OrderDestroyAPIView, OrderUpdateAPIView,
                          OrderRetrieveAPIView, OrderListView, OrderCreateView, OrderDeleteView, OrderEditView, OrderStatusUpdateView, RevenueReportView)

app_name = OrdersConfig.name

urlpatterns = [
    path('api/add/', OrderCreateAPIView.as_view(),name='add_order_api'),
    path('api/list_orders/', OrderListAPIView.as_view(),name='order_list_api'),
    path('api/retrieve_order/<int:pk>/', OrderRetrieveAPIView.as_view(),name='retrieve_order_api'),
    path('api/edit_order/<int:pk>/', OrderUpdateAPIView.as_view(), name='edit_order_api'),
    path('api/delete_order/<int:pk>/', OrderDestroyAPIView.as_view(), name='delete_order_api'),

    path('', OrderListView.as_view(), name='order_list'),
    path('add/', OrderCreateView.as_view(), name='add_order'),
    path('delete/<int:pk>/', OrderDeleteView.as_view(), name='delete_order'),
    path('update_status/<int:order_id>/', OrderStatusUpdateView.as_view(), name='update_status'),
    path('edit/<int:pk>/', OrderEditView.as_view(), name='edit_order'),
    path('revenue/', RevenueReportView.as_view(), name='revenue_report'),
]

orders/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models.signals import m2m_changed
from django.dispatch import receiver
from items.models import Item

"""Модель заказа"""
class Order(models.Model):
    STATUS_CHOICES = [
        ('pending', 'В ожидании'),
        ('ready', 'Готово'),
        ('paid', 'Оплачено'),
    ]

    table_number = models.IntegerField(validators=[MinValueValidator(1)], verbose_name='номер стола')
    items = models.ManyToManyField(Item, verbose_name='блюда')
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name='сумма заказа')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending', verbose_name='статус заказа')

    def save(self, *args, **kwargs):
        is_new = self.pk is None
        super().save(*args, **kwargs)

        if is_new or self.pk:
            self.update_total_price()

    def update_total_price(self):
        total = self.items.aggregate(models.Sum('price'))['price__sum'] or 0
        self.total_price = total
        super().save(update_fields=["total_price"])

    def __str__(self):
        return f"Заказ {self.id} - Стол {self.table_number}"

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'


@receiver(m2m_changed, sender=Order.items.through)
def update_order_total(sender, instance, action, **kwargs):
    if action in ['post_add', 'post_remove', 'post_clear']:
        instance.update_total_price()

orders/forms.py
from django import forms

from items.models import Item
from .models import Order

"""Форма для создания заказа"""
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['table_number', 'items']

    items = forms.ModelMultipleChoiceField(
        queryset=Item.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True,
        label="Выберите блюда"
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['items'].error_messages = {
            'required': 'Пожалуйста, выберите хотя бы одно блюдо!',
        }

    def get_errors(self):
        error_messages = {}
        for field, errors in self.errors.items():
            error_messages[field] = [self._get_custom_error_message(error) for error in errors]
        return error_messages

    def _get_custom_error_message(self, error):
        if error == 'This field is required.':
            return 'Это поле обязательно для заполнения!'
        return error

"""Форма для редактирования заказа"""
class OrderEditForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['items']

    items = forms.ModelMultipleChoiceField(
        queryset=Item.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True,
        label="Выберите блюда"
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['items'].error_messages = {
            'required': 'Пожалуйста, выберите хотя бы одно блюдо!',
        }

    def get_errors(self):
        error_messages = {}
        for field, errors in self.errors.items():
            error_messages[field] = [self._get_custom_error_message(error) for error in errors]
        return error_messages

    def _get_custom_error_message(self, error):
        if error == 'This field is required.':
            return 'Это поле обязательно для заполнения!'
        return error

class OrderStatusForm(forms.Form):
    STATUS_CHOICES = [
        ('pending', 'Ожидание'),
        ('ready', 'Готов'),
        ('paid', 'Оплачен')
    ]
    status = forms.ChoiceField(choices=STATUS_CHOICES)

orders/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, View
from django.urls import reverse_lazy
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.edit import FormView
from rest_framework import viewsets, generics
from items.models import Item
from orders.models import Order
from orders.serializers import OrderSerializer
from orders.forms import OrderForm, OrderStatusForm, OrderEditForm
from django.db.models import Sum
from django.http import JsonResponse

"""API Эндпоинты для работы с заказом"""
class OrderCreateAPIView(generics.CreateAPIView):
    queryset = Order.objects.prefetch_related('items')
    serializer_class = OrderSerializer

    def perform_create(self, serializer):
        order = serializer.save()
        return order

class OrderListAPIView(generics.ListAPIView):
    queryset = Order.objects.prefetch_related('items')
    serializer_class = OrderSerializer


class OrderRetrieveAPIView(generics.RetrieveAPIView):
    queryset = Order.objects.prefetch_related('items')
    serializer_class = OrderSerializer


class OrderUpdateAPIView(generics.UpdateAPIView):
    queryset = Order.objects.prefetch_related('items')
    serializer_class = OrderSerializer


class OrderDestroyAPIView(generics.DestroyAPIView):
    queryset = Order.objects.prefetch_related('items')


"""Эндпоинт для вывода списка заказов"""
class OrderListView(ListView):
    model = Order
    template_name = "order_list.html"
    context_object_name = "orders"

    def get_queryset(self):
        status_filter = self.request.GET.get('status', '').strip()
        search_query = self.request.GET.get('search', '').strip()
        orders = Order.objects.prefetch_related('items')

        if status_filter:
            orders = orders.filter(status=status_filter)

        if search_query:
            if search_query.isdigit():
                orders = orders.filter(table_number=search_query)
            else:
                orders = orders.filter(status__icontains=search_query)

        return orders.order_by('id')

"""Эндпоинт для создания заказов"""
class OrderCreateView(CreateView):
    model = Order
    form_class = OrderForm
    template_name = "add_order.html"
    success_url = reverse_lazy("orders:order_list")

    def form_valid(self, form):
        order = form.save()
        order.update_total_price()
        messages.success(self.request, f"Заказ №{order.id} успешно создан")
        return redirect(self.success_url)

    def form_invalid(self, form):
        messages.error(self.request, "Пожалуйста, исправьте ошибки ниже.")
        return self.render_to_response(self.get_context_data(form=form, errors=form.get_errors()))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["items"] = Item.objects.all()
        return context

"""Эндпоинт для удаления заказов"""
class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy("orders:order_list")

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

"""Эндпоинт для редактирования заказов"""
class OrderEditView(UpdateView):
    model = Order
    form_class = OrderEditForm
    template_name = "edit_order.html"
    success_url = reverse_lazy("orders:order_list")

    def form_valid(self, form):
        selected_items = self.request.POST.getlist("items")

        if not selected_items:
            messages.error(self.request, "Выберите хотя бы одно блюдо")
            return self.form_invalid(form)

        order = form.save()
        order.update_total_price()
        order.items.set(Item.objects.filter(id__in=selected_items))
        messages.success(self.request, f"Заказ №{order.id} успешно обновлен")
        return redirect(self.get_success_url())

    def form_invalid(self, form):
        messages.error(self.request, "Пожалуйста, исправьте ошибки ниже.")
        return self.render_to_response(self.get_context_data(form=form, errors=form.get_errors()))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["items"] = Item.objects.all()
        return context

"""Эндпоинт для обновления статуса заказов"""
@method_decorator(csrf_exempt, name='dispatch')
class OrderStatusUpdateView(FormView):
    form_class = OrderStatusForm

    def post(self, request, *args, **kwargs):
        order = get_object_or_404(Order, id=self.kwargs["order_id"])
        form = self.get_form()

        if form.is_valid():
            new_status = form.cleaned_data["status"]
            if new_status in ["pending", "ready", "paid"]:
                order.status = new_status
                order.save()
                return JsonResponse({"success": True})

        return JsonResponse({"success": False}, status=400)

"""Эндпоинт для рассчета выручки за смену"""
class RevenueReportView(View):
    template_name = "revenue_report.html"

    def get(self, request):
        paid_orders = Order.objects.filter(status='paid').prefetch_related('items')
        total_revenue = paid_orders.aggregate(total_revenue=Sum('total_price'))['total_revenue'] or 0
        return render(request, self.template_name, {'paid_orders': paid_orders, 'total_revenue': total_revenue})

orders/templates/add_order.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Add Order</title>
    <link rel="stylesheet" type="text/css" href="/static/css/add_style.css?v=2">
</head>
<body>
    <h1>Добавить заказ</h1>
    <form method="POST" class="search-form">
        {% csrf_token %}

        <label for="table_number">Номер стола:
            <input type="text" id="table_number" placeholder="№" name="table_number" required>
        </label><br>

        <h3>Выберите блюда:</h3>
        {% for item in items %}
            <div class="checkbox-container">
                <input type="checkbox" id="item_{{ item.id }}" name="items" value="{{ item.id }}">
                <label for="item_{{ item.id }}">{{ item.title }} - {{ item.price }}</label>
            </div>
        {% endfor %}

        {% if form.errors %}
            <div class="form-errors">
                {% for field in form %}
                    {% if field.errors %}
                        <div class="field-error">
                            {% for error in field.errors %}
                                <p class="custom-error-message">{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}

        <button type="submit">Добавить заказ</button>
    </form>

    <a href="/">Назад</a>
</body>
</html>

orders/templates/edit_order.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Update Order</title>
    <link rel="stylesheet" type="text/css" href="/static/css/add_style.css?v=2">
</head>
<body>
    <h1>Редактирование заказа №{{ order.id }}</h1>
    <form method="post">
        {% csrf_token %}
        <label>Номер стола: {{ order.table_number }}</label>
        <h3>Выберите блюда:</h3>
        {% for item in items %}
            <div class="checkbox-container">
                <input type="checkbox" id="item_{{ item.id }}" name="items" value="{{ item.id }}"
                {% if item in order.items.all %}checked{% endif %}>
                    {{ item.title }} - {{ item.price }} руб.
            </div>
        {% endfor %}

        {% if form.errors %}
            <div class="form-errors">
                {% for field in form %}
                    {% if field.errors %}
                        <div class="field-error">
                            {% for error in field.errors %}
                                <p class="custom-error-message">{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}

        <button type="submit">Сохранить</button>
    </form>
    <a href="/">Назад</a>
</body>
</html>

orders/templates/order_list.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Order List</title>
    <link rel="stylesheet" type="text/css" href="/static/css/style.css?v=2">
</head>
<body>
    <h1>Список заказов</h1>
    <a href="/add/" class="button">Добавить заказ</a>
    <a href="{% url 'orders:revenue_report' %}" class="button">Выручка за смену</a>

    <form method="get" class="search-form">
        <input type="text" name="search" placeholder="Поиск по номеру стола" value="{{ request.GET.search }}">
        <select name="status">
            <option value="">Все</option>
            <option value="pending" {% if request.GET.status == "pending" %}selected{% endif %}>В ожидании</option>
            <option value="ready" {% if request.GET.status == "ready" %}selected{% endif %}>Готово</option>
            <option value="paid" {% if request.GET.status == "paid" %}selected{% endif %}>Оплачено</option>
        </select>
        <button type="submit">Поиск</button>
    </form>

    <table class="container">
        <thead>
            <tr>
                <th><h2>ID</h2></th>
                <th><h2>Стол</h2></th>
                <th><h2>Блюда</h2></th>
                <th><h2>Сумма</h2></th>
                <th><h2>Статус</h2></th>
                <th><h2>Действия</h2></th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.table_number }}</td>
                <td>
                    <ul class="markers">
                        {% for item in order.items.all %}
                            <li>{{ item.title }} - {{ item.price }} руб.</li>
                        {% endfor %}
                    </ul>
                </td>
                <td>{{ order.total_price }} руб.</td>
                <td class="status">{{ order.get_status_display }}</td>
                <td>
                    <button class="update-status" data-order-id="{{ order.id }}" data-status="{{ order.status }}">Изменить статус</button>
                    <a href="{% url 'orders:edit_order' order.id %}" class="edit">Редактировать</a>
                    <button class="delete-order" data-order-id="{{ order.id }}">Удалить</button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div id="status-modal" class="modal">
        <div class="modal-content">
            <h2>Изменить статус заказа</h2>
            <form id="status-form" method="post">
                {% csrf_token %}
                <input type="hidden" name="order_id" id="order-id">
                <select name="status" id="statusSelect">
                    <option value="pending">В ожидании</option>
                    <option value="ready">Готово</option>
                    <option value="paid">Оплачено</option>
                </select>
                <button class="update" type="submit" id="saveStatus">Обновить</button>
            </form>
            <button class="close" id="closeModal">Закрыть</button>
        </div>
    </div>

    <div id="delete-modal" class="delete-modal">
        <div class="delete-modal-content">
            <h2>Удалить заказ?</h2>
            <form id="delete-form" method="post">
                {% csrf_token %}
                <input type="hidden" name="order_id" id="delete-order-id">
                <button type="submit" id="confirmDelete">Удалить</button>
                <button type="button" id="cancelDelete">Отмена</button>
            </form>
        </div>
    </div>
    <script src="/static/js/script.js"></script>
</body>
</html>

orders/templates/revenue_report.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Revenue</title>
    <link rel="stylesheet" type="text/css" href="/static/css/style.css?v=2">
</head>
<body>
    <h1>Выручка за смену</h1>

    <h2>Список оплаченных заказов</h2>
    <table class="container">
        <thead>
            <tr>
                <th><h2>ID</h2></th>
                <th><h2>Стол</h2></th>
                <th><h2>Блюда</h2></th>
                <th><h2>Сумма</h2></th>
            </tr>
        </thead>
        <tbody>
            {% for order in paid_orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.table_number }}</td>
                <td>
                    <ul class="markers">
                        {% for item in order.items.all %}
                            <li>{{ item.title }} - {{ item.price }} руб.</li>
                        {% endfor %}
                    </ul>
                </td>
                <td>{{ order.total_price }} руб.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <p><strong>Общая сумма оплаченных заказов:</strong>  {{ total_revenue }} руб.</p>

    <a href="/" class="button">Назад</a>
</body>
</html>

orders/templates/update_status.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Update Status</title>
</head>
<body>
    <h1>Изменить статус заказа</h1>
    <form method="post">
        {% csrf_token %}
        <select name="status">
            <option value="pending">В ожидании</option>
            <option value="ready">Готово</option>
            <option value="paid">Оплачено</option>
        </select>
        <button type="submit">Обновить</button>
    </form>
    <a href="/">Назад</a>
</body>
</html>